baseURL = "http://www.carlxu.cn"
title = "Carl xu's Blog"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
paginate = 9999
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
    author = "Carl xu"
    description = "Carl xu's personal website"
    keywords = "blog,developer,personal"
    info = ["Being Full Stack Developer", "Big Orange", "Small Atom"]
    avatarURL = "images/avatar.png"
    logoImg = "images/avatar.png"
    #gravatar = "john.doe@example.com"
    #footerContent = "Enter a text here."
    dateFormat = "2006-01-02"
    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2016


# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
    # Right To Left, shift content direction for languagues such as Arabic
    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false
    # Series see also post count
    maxSeeAlsoItems = 6
    # Enable Twemoji
    enableTwemoji = false
    # Custom CSS
    customCSS = []
    # Custom SCSS
    customSCSS = []
    # Custom JS
    customJS = []


[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

# Comments on github issue
[params.utteranc]
    repo = "nicxzq/carlxu.cn"
    issue-term = "pathname"
    theme = "github-light"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/nicxzq/"

[[params.social]]
    name = "WeChat"
    icon = "fa fa-weixin"
    weight = 2
    #url = "https://medium.com/@johndoe"

#[[params.social]]
#    name = "ZhiHu"
#    icon = "fa fa-zhihu"
#    weight = 3
#    url = "https://zhuanlan.zhihu.com/nicxzq"

[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 4
    url = "https://carlxu.cn/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[languages.zh-cn]
    languageName = "中文"
    title = "Carlxu的个人博客"

    [languages.zh-cn.params]
        author = "Carl xu"
        info = ["Being Full-Stack Developer", "大橙小原"]

        description = "通过学习（GTD、时间管理、知识管理、写作、财务管理）、技术创造（前端、后端、移动端、DevOps）、育儿（儿童心理、幼儿启蒙、学前教育、陪伴成长）、投资（指数投资、基金、股票、债券）来建立被动收入、培育健康的下一代"
        keywords = "自我提升、时间管理、GTD、写作、笔记管理、知识管理、家庭教育、财务管理、全栈开发、被动收入"
        # footerContent = "self/dev/money"

    [[languages.zh-cn.menu.main]]
        name = "关于"
        weight = 1
        url = "/about/"

    [[languages.zh-cn.menu.main]]
        name = "学习"
        weight = 2
        url = "/self/"

    [[languages.zh-cn.menu.main]]
        name = "技术"
        weight = 3
        url = "/dev/"

    [[languages.zh-cn.menu.main]]
        name = "育儿"
        weight = 4
        url = "/rear/"

    [[languages.zh-cn.menu.main]]
        name = "投资"
        weight = 5
        url = "/money/"

    [[languages.zh-cn.menu.main]]
        name = "随笔"
        weight = 6
        url = "/essay/"

[languages.en]
    languageName = "English"

    [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

    [[languages.en.menu.main]]
        name = "Self"
        weight = 2
        url = "/self/"

    [[languages.en.menu.main]]
        name = "Dev"
        weight = 3
        url = "/dev/"

    [[languages.en.menu.main]]
        name = "Rear"
        weight = 4
        url = "/rear/"

    [[languages.en.menu.main]]
        name = "Money"
        weight = 5
        url = "/money/"

    [[languages.en.menu.main]]
        name = "Essay"
        weight = 6
        url = "/essay/"